---
layout: default
title: Aurelia TamÃ²-Larrieux
---

# Aurelia TamÃ²-Larrieux

Professor of Law & Technology (University of Lausanne).  
Leads the **Legal Design & Code Lab**. 

- ğŸ“˜ Book: *AI and Law: How Automation is Changing the Law* (Routledge)
- ğŸ§ª Lab: Legal Design & Code Lab (https://wp.unil.ch/legaldesignandcodelab/)
- ğŸ” Teaching: Law and Computation (EPFL), Digital Transformation of Law (UNIL), AI Governance (UNIL), AI Governance & Regulatory Frameworks (EPFL/UNIL), Legal Challenges in the Digital Economy (UNIL)
- ğŸ“˜ Research: Data and AI regulation and governance, legal automation, access to justice and legal design, data access, evidenced-based policy making, trust in automation
- ğŸ›ï¸ Policy: AI governance in Switzerland
- âœ‰ï¸ Contact: aurelia.tamo-larrieux(at)@unil.ch
